plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.pianopdfparser'
version = '0.1.0'

android {
  namespace "expo.modules.pianopdfparser"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    externalNativeBuild {
      cmake {
        cppFlags "-std=c++17"
        arguments "-DANDROID_STL=c++_shared"
      }
    }
    ndk {
      abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
    }
  }
  externalNativeBuild {
    cmake {
      path "CMakeLists.txt"
    }
  }
  lintOptions {
    abortOnError false
  }
}
